CREATE TABLE IF NOT EXISTS `uctoo_yuyue` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`yTime`  int(10) NOT NULL  COMMENT '预约时间',
`market`  varchar(255) NOT NULL  COMMENT '门店',
`phone`  varchar(32) NOT NULL  COMMENT '手机',
`item`  varchar(255) NOT NULL  COMMENT '预约项目',
`token`  varchar(255) NOT NULL  COMMENT 'Token',
`cTime`  int(10) UNSIGNED NOT NULL  COMMENT '创建时间',
`number`  int(10) NOT NULL  COMMENT '预约人数',
`mTime`  int(10) NOT NULL  COMMENT '修改时间',
`name`  varchar(255) NOT NULL  COMMENT '联系人',
`status`  int(10) NOT NULL  DEFAULT 1 COMMENT '状态',
`remark`  varchar(2000) NOT NULL  COMMENT '备注',
`memo`  varchar(2000) NOT NULL  COMMENT '备忘',
`openid`  varchar(255) NOT NULL  COMMENT '粉丝openid',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `uctoo_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('yuyue','预约','0','','1','{"1":["keyword","keyword_type","title","intro","cover","content"]}','1:基础','','','','','keyword:关键词\r\nkeyword_type|get_name_by_status:关键词类型\r\ntitle:标题\r\ncTime|time_format:发布时间\r\nid:操作:[EDIT]|编辑,[DELETE]|删除','10','title','','1396061373','1404779296','1','MyISAM');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('yTime','预约时间','int(10) NOT NULL','datetime','','','1','','0','0','1','1404779515','1404779515','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('market','门店','varchar(255) NOT NULL','string','','','1','','0','1','1','1404779477','1404779477','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('phone','手机','varchar(32) NOT NULL','string','','','1','','0','0','1','1404893653','1404892867','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('item','预约项目','varchar(255) NOT NULL','string','','','1','','0','1','1','1404779426','1404779426','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(255) NOT NULL','string','','','0','','0','0','1','1396602871','1396602859','','3','','regex','get_token','1','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cTime','创建时间','int(10) UNSIGNED NOT NULL','datetime','','','0','','0','0','1','1404779540','1396075102','','3','','regex','time','1','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('number','预约人数','int(10) NOT NULL','num','','','1','','0','0','1','1404889981','1404889981','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('mTime','修改时间','int(10) NOT NULL','datetime','','','0','','0','0','1','1396624664','1396624664','','3','','regex','time','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('name','联系人','varchar(255) NOT NULL','string','','','1','','0','0','1','1404891988','1404891988','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('status','状态','int(10) NOT NULL','num','1','','1','','0','1','1','1404779677','1404779659','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('remark','备注','varchar(2000) NOT NULL','string','','','1','','0','0','1','1404780314','1396061859','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('memo','备忘','varchar(2000) NOT NULL','string','','','1','','0','0','1','1404780297','1404780237','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('openid','粉丝openid','varchar(255) NOT NULL','string','','','1','','0','0','1','1404891789','1404891789','','3','','regex','','3','function');
UPDATE `uctoo_attribute` SET model_id= (SELECT MAX(id) FROM `uctoo_model`) WHERE model_id=0;
INSERT INTO `uctoo_keyword` (`keyword`,`token`,`addon`,`aim_id`,`cTime`,`keyword_type`,`extra_text`,`extra_int`,`keyword_length`) VALUES ('预约查询', '0', 'YuYue', '0', '1404949702', '0', '', '0','4');
INSERT INTO uctoo_credit_config(title,name,mTime,experience,score,token) VALUES ('预约', 'yuyue', '1404652709', '0', '0', '0');
